name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Node Packages
        run: npm install

      - name: Genereate static website files
        run: npm run build

      - name: Deploy to Cloudflare Pages Production
        if: github.ref == 'refs/heads/master'
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: e40ca42475e880f2bb8fef31bc321e4c
          projectName: kris-clrs4e
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Deploy to Cloudflare Pages Preview
        if: github.ref != 'refs/heads/master'
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: e40ca42475e880f2bb8fef31bc321e4c
          projectName: kris-clrs4e
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}